// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCTMcxovM3ffDTF__LG1kZhStN8NepGaA',
    appId: '1:368484872971:web:56cf170501ad8bbc35280e',
    messagingSenderId: '368484872971',
    projectId: 'study-app-6037c',
    authDomain: 'study-app-6037c.firebaseapp.com',
    storageBucket: 'study-app-6037c.appspot.com',
    measurementId: 'G-8LCG95VL6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEofcn5g72M8r0EBu9ujqr3ad9Rh-euiY',
    appId: '1:368484872971:android:dde3c66f83bc695a35280e',
    messagingSenderId: '368484872971',
    projectId: 'study-app-6037c',
    storageBucket: 'study-app-6037c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkd3RbWHhrjNQn0Y-x-EGQvHHWVZMoMWA',
    appId: '1:368484872971:ios:8c3cbc88eda2575b35280e',
    messagingSenderId: '368484872971',
    projectId: 'study-app-6037c',
    storageBucket: 'study-app-6037c.appspot.com',
    androidClientId: '368484872971-fhg15l79q56brqnced3hbm4icr75ae9g.apps.googleusercontent.com',
    iosClientId: '368484872971-k38gkbg9u1apraeg92upqg4mgj7jh34c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );
}
